version: "3.8"
services:
  sqlserver:
    build: ./Db
    platform: linux/amd64
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "password123!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./Db:/usr/src/app
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1GB"

  app:
    build: ./back
    ports:
      - "3001:3001"
    environment:
      DB_HOST: sqlserver
      DB_USER: sa
      DB_PASS: password123!
      DB_NAME: database
      JWT_TOKEN: "secret"
    depends_on:
      - sqlserver
    volumes:
      - ./back:/app
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1GB"
