apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver # name of the StatefulSet workload, the SQL Server instance name is derived from this. We suggest to keep this name same as the .spec.template.metadata.labels, .spec.selector.matchLabels and .spec.serviceName to avoid confusion.
spec:
  replicas: 1 # only one pod, with one SQL Server instance deployed.
  selector:
    matchLabels:
      app: sqlserver # this has to be the same as .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: sqlserver # this has to be the same as .spec.selector.matchLabels, as documented [here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/):
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: sqlserver # container name within the pod.
          image: hramos13/ubi-final-project-sqlserver
          ports:
            - containerPort: 1433
              name: tcpsql
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_ENABLE_HADR
              value: "1"
            - name: MSSQL_AGENT_ENABLED
              value: "1"
            - name: MSSQL_SA_PASSWORD
              value: "password123!"

---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  type: ClusterIP
  selector:
    app: sqlserver
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
